"""Per-policy test batteries: the requests to send a proxy's Mule app, and what Apigee would answer.

:func:`build_battery` reads the proxy's IR and its generated project and
returns one or more cases per policy a2m can test, each a short series of
calls with the expected status of every call, the number of calls the mock
backend must receive and the headers those calls must (or must not) carry.
Expectations come from the proxy's own policies (:mod:`a2m.verify.sim`),
never from the generated app, so the battery checks the app against Apigee's
behaviour. Limits and names come from the proxy's settings: the rate of a
SpikeArrest, the allowance of a Quota, where a VerifyAPIKey reads its key.

Situations per policy type:

* SpikeArrest: under-limit, over-limit (N calls spaced by the pace interval
  pass, one more sent right away gets 429);
* Quota: within-allowance, over-allowance (the allowance plus one call);
* VerifyAPIKey: valid-key, missing-key, bad-key; the valid key is the first
  allowed key in the generated properties file, or a test key the runner sets
  in the deployed copy when that list is empty;
* AssignMessage: header-set (only when no other case already checks the
  headers it sets on the backend call), condition-false (its step's condition
  is false, so the header is not set);
* ExtractVariables: extracted-value-used (a value it extracts reaches the
  backend through a later step; only when no other case already shows it);
* RaiseFault: fault-raised; BasicAuthentication (Decode): correct-credentials,
  missing-credentials; AccessControl: denied-address or allowed-address for
  the local test address; ResponseCache: repeated-call-cached (three
  identical calls, one backend hit), once a2m generates it.

Cases exist only for steps a2m generated and that run in the app, decided
from the generator's own per-step records (:mod:`a2m.verify.generated`), never
from the policy type: a step a2m did not generate (ResponseCache, which has no
Mule template yet, a template that skipped the step with the request changes
made before it, ...) or generated where it never runs (its condition, or the
condition of its Flow or RouteRule, can't be translated, so its ``when`` is
``#[false]``) is listed as untested with the reason "not generated by a2m",
never run as a case the app can only fail. When a policy has several steps,
the first one that runs in the app is tested. A case whose request, in Apigee,
runs another step the app does not run (not generated, or never runs there) is
untested too: what Apigee does for it is not what the app was made to do.

Whatever cannot be tested is listed in :attr:`Battery.untested` with the
reason, so every policy of the proxy has at least one case or an entry there.
A case whose expected answer is an error while the endpoint has a FaultRule or
DefaultFaultRule is untested too: those rules may change the error response,
and a2m does not simulate them (:mod:`a2m.verify.sim`).

:func:`recorded_key_properties` does for a golden replay what the battery does
with its test key: when a VerifyAPIKey's allowed-keys property is empty, the
keys the recorded requests presented (and Apigee did not answer 401) are
allowed in the deployed copy only.
"""

from __future__ import annotations

import base64
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import parse_qs, urlsplit

from a2m.conditions import ANY
from a2m.conditions.parser import Node
from a2m.ir import Bundle, Policy, ProxyEndpoint, TargetEndpoint
from a2m.policies import registry
from a2m.policies.common import key_part
from a2m.verify.generated import GeneratedSteps
from a2m.verify.model import HttpRequest, ReviewFlag, UntestedPolicy, fold
from a2m.verify.sim import (
    NO_EFFECT_TYPES,
    REQUEST,
    CaseState,
    FaultRuleUnknown,
    Model,
    Outcome,
    Placed,
    Req,
    Unknown,
    child,
    children,
    parse_condition,
    quota_allowance,
    sample_pattern_value,
    satisfy,
    spike_rate,
    text,
)

PROPERTIES_PATH = ("src", "main", "resources", "config.properties")
TEST_KEY = "a2m-battery-key"
BAD_KEY = "a2m-invalid-key"
TEST_USER, TEST_PASSWORD = "a2m-user", "a2m-password"
# Spacing between calls: the slowest SpikeArrest pace interval times this, plus a little.
PACE_FACTOR = 1.25
PACE_EXTRA = 0.05
# A too-soon call can only be timed when the pace interval is at least this long.
MIN_SPIKE_INTERVAL = 0.1
MAX_SPIKE_CALLS = 10
MAX_QUOTA_ALLOWANCE = 200
MAX_CASE_SECONDS = 60.0
CACHE_CALLS = 3
TIME_WINDOW_TYPES = ("SpikeArrest", "Quota")
UNIT_WORDS = {"ps": "per second", "pm": "per minute"}
# The write-model entry for "every header" and the prefix of a response header write (a2m.policies.registry).
ANY_HEADER = ANY
RESPONSE_HEADER_PREFIX = "response.header."


@dataclass(frozen=True, slots=True)
class BatteryCall:
    """One call of a case. ``immediate``: sent right after the previous call, without the pacing wait."""

    request: HttpRequest
    expected_status: int
    expected_body: bytes | None = None
    immediate: bool = False


@dataclass(frozen=True, slots=True)
class BatteryCase:
    name: str
    policy: str
    policy_type: str
    situation: str
    calls: tuple[BatteryCall, ...]
    expected_backend_calls: int
    # Headers every backend call of the case must carry with this value (None: must be absent).
    expected_backend_headers: Mapping[str, str | None] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class Battery:
    cases: tuple[BatteryCase, ...]
    untested: tuple[UntestedPolicy, ...]
    # Settings the deployed app needs for these cases (e.g. a test API key when no key is configured).
    properties: Mapping[str, str] = field(default_factory=dict)
    # Seconds to wait between calls (0 without a SpikeArrest).
    pace_seconds: float = 0.0
    # Run every case on a freshly started app (counters and caches that would carry over between cases).
    isolate: bool = False
    # What the battery set up that the report should say (e.g. a test API key it allowed).
    notes: tuple[str, ...] = ()


def read_properties(app_dir: Path) -> dict[str, str]:
    """The generated properties file's ``key=value`` lines (single-line values, as a2m writes them)."""
    path = app_dir.joinpath(*PROPERTIES_PATH)
    try:
        lines = path.read_text(encoding="latin-1").splitlines()
    except OSError:
        return {}
    props: dict[str, str] = {}
    for raw in lines:
        line = raw.strip()
        if not line or line[0] in "#!":
            continue
        cut = min((i for i in (line.find("="), line.find(":")) if i >= 0), default=-1)
        if cut >= 0:
            props[line[:cut].strip()] = line[cut + 1 :].strip()
    return props


def time_window_flags(bundle: Bundle) -> tuple[ReviewFlag, ...]:
    """A review flag for every SpikeArrest and Quota a step uses: a short test cannot prove a time window."""
    used = {placed.step.policy for placed in Model(bundle, {}).placed_steps()}
    flags: list[ReviewFlag] = []
    for policy in bundle.policies:
        if policy.name not in used or policy.type not in TIME_WINDOW_TYPES:
            continue
        if policy.type == "SpikeArrest":
            rate = spike_rate(policy)
            what = (
                f"allows {rate[0]} {UNIT_WORDS[rate[1]]} ({rate[0]}{rate[1]})" if rate is not None else
                "has a rate a2m could not read"
            )
            reason = (
                f"SpikeArrest {policy.name} {what}; a short test checks the pacing of a few calls, not the rate "
                "over time, so check it by hand"
            )
        else:
            allowance = quota_allowance(policy)
            what = (
                f"allows {allowance[0]} calls per {allowance[1]} {allowance[2]}" if allowance is not None else
                "has an allowance a2m could not read"
            )
            reason = (
                f"Quota {policy.name} {what}; a short test cannot prove when the window starts and resets, so "
                "check it by hand"
            )
        flags.append(ReviewFlag(policy.name, policy.type, reason))
    return tuple(flags)


def build_battery(bundle: Bundle, app_dir: Path, *, generated: GeneratedSteps | None = None) -> Battery:
    """The battery for ``bundle``'s app in ``app_dir``; ``generated`` is what the generator made of each step
    (default: :meth:`GeneratedSteps.planned`, the generator's records without an AI provider)."""
    return _Builder(bundle, app_dir, generated if generated is not None else GeneratedSteps.planned(bundle)).build()


@dataclass
class _Draft:
    case: BatteryCase
    order: tuple[int, int]
    writers: frozenset[str]
    fed_by: frozenset[str]


class _Builder:
    def __init__(self, bundle: Bundle, app_dir: Path, generated: GeneratedSteps) -> None:
        self.bundle = bundle
        self.generated = generated
        props = read_properties(app_dir)
        self.properties: dict[str, str] = {}
        self.notes: list[str] = []
        self.valid_key: dict[str, str] = {}
        allowed_everywhere: set[str] = set()
        for policy in bundle.policies:
            if policy.type != "VerifyAPIKey":
                continue
            prop = f"verifyapikey.{key_part(policy.name)}.allowedKeys"
            keys = [k.strip() for k in props.get(prop, "").split(",") if k.strip()]
            allowed_everywhere.update(keys)
            if keys:
                self.valid_key[policy.name] = keys[0]
            else:
                self.valid_key[policy.name] = TEST_KEY
                if prop in props:
                    self.properties[prop] = TEST_KEY
                    self.notes.append(
                        f"VerifyAPIKey {policy.name} has no allowed key in {PROPERTIES_PATH[-1]}, so the tests allowed "
                        f"the key {TEST_KEY} in the deployed copy only"
                    )
        self.bad_key = BAD_KEY
        while self.bad_key in allowed_everywhere or self.bad_key == TEST_KEY:
            self.bad_key += "-x"
        self.model = Model(bundle, {name: (key,) for name, key in self.valid_key.items()})
        self.policies = {p.name: p for p in bundle.policies}
        self.untested: list[UntestedPolicy] = []
        self.drafts: list[_Draft] = []
        # Policies another case already checks (the headers an AssignMessage sets, a value an ExtractVariables reads).
        self.covered: set[str] = set()
        self.pace = self._pace()
        # Why each step (by its key) does not run in the app, for the steps that don't (see _not_live).
        self.not_live: dict[str, str] = {}
        for item in self.model.placed_steps():
            why = self._not_live(item)
            if why is not None:
                self.not_live[item.key] = why

    # ------------------------------------------------------------ the whole battery

    def build(self) -> Battery:
        placed = self.model.placed_steps()
        first: dict[str, tuple[int, Placed]] = {}
        for index, item in enumerate(placed):
            known = first.get(item.step.policy)
            # The first step of the policy that runs in the app (else its first step, which says why not).
            if known is None or (known[1].key in self.not_live and item.key not in self.not_live):
                first[item.step.policy] = (index, item)
        later_types = ("ExtractVariables", "AssignMessage")
        for phase in (None, *later_types):
            for name, (index, item) in first.items():
                policy = self.policies.get(name)
                if policy is None:
                    continue
                if (phase is None and policy.type in later_types) or (phase is not None and policy.type != phase):
                    continue
                self._cases_for(policy, item, index)
        tested = {d.case.policy for d in self.drafts} | self.covered
        noted = {u.name for u in self.untested}
        in_fault_rules = fault_rule_policies(self.bundle)
        for policy in self.bundle.policies:
            if policy.name in tested or policy.name in noted:
                continue
            if not policy.enabled:
                reason = "it is disabled (enabled=false)"
            elif policy.name in in_fault_rules:
                reason = "it runs only in a FaultRule or DefaultFaultRule, which the battery does not simulate"
            else:
                reason = "no flow step uses it"
            self.untested.append(UntestedPolicy(policy.name, policy.type, reason))
        drafts = sorted(self.drafts, key=lambda d: d.order)
        isolate = any(d.case.policy_type in ("Quota", "ResponseCache") for d in drafts)
        return Battery(
            cases=tuple(d.case for d in drafts),
            untested=tuple(self.untested),
            properties=dict(self.properties),
            pace_seconds=self.pace,
            isolate=isolate,
            notes=tuple(self.notes),
        )

    def _pace(self) -> float:
        slowest = 0.0
        for policy in self.bundle.policies:
            rate = spike_rate(policy) if policy.type == "SpikeArrest" and policy.enabled else None
            if rate is not None:
                slowest = max(slowest, (1.0 if rate[1] == "ps" else 60.0) / rate[0])
        return slowest * PACE_FACTOR + PACE_EXTRA if slowest else 0.0

    def _skip(self, policy: Policy, reason: str) -> None:
        self.untested.append(UntestedPolicy(policy.name, policy.type, reason))

    def _not_live(self, item: Placed) -> str | None:
        """Why ``item``'s step does not run in the generated app (from the generator's records), or None."""
        route: str | None = None
        kind, name = item.endpoint.split(":", 1)
        if kind == "target":
            endpoint = self.model.endpoint_of(item)
            rule = next((r for r in endpoint.route_rules if r.target == name), None) if endpoint else None
            if endpoint is not None and rule is not None:
                route = f"{endpoint.name}/{rule.name}"
        part = item.key.split("/")[1]
        return self.generated.step_problem(item.step.name, item.endpoint, item.flow, part, item.side, route)

    def _disabled_on_the_way(self, outcomes: Sequence[Outcome], own: str) -> str | None:
        """A step (other than ``own``'s policy) the predicted calls run in Apigee that the app does not run."""
        for outcome in outcomes:
            for key in outcome.executed:
                why = self.not_live.get(key)
                if why is None:
                    continue
                step = next((p for p in self.model.placed_steps() if p.key == key), None)
                if step is None or step.step.policy == own:
                    continue
                policy = self.policies.get(step.step.policy)
                if policy is not None and policy.type in NO_EFFECT_TYPES:
                    continue
                return f"in Apigee its request also runs step {step.step.name}, which the app does not run ({why})"
        return None

    # ------------------------------------------------------------ requests

    def _with_credentials(self, req: Req) -> Req:
        """``req`` with every valid API key, Basic credentials and value an ExtractVariables reads."""
        for policy in self.bundle.policies:
            if not policy.enabled:
                continue
            if policy.type == "VerifyAPIKey":
                req = self._set_ref(req, _api_key_ref(policy), self.valid_key.get(policy.name, TEST_KEY))
            elif policy.type == "BasicAuthentication" and fold(text(child(policy.settings, "Operation")) or "") == "decode":
                token = base64.b64encode(f"{TEST_USER}:{TEST_PASSWORD}".encode()).decode("ascii")
                req = self._set_ref(req, text(child(policy.settings, "Source")) or "", f"Basic {token}")
            elif policy.type == "ExtractVariables":
                for item in policy.settings.children:
                    patterns = children(item, "Pattern")
                    name = item.attributes.get("name", "")
                    if item.tag in ("QueryParam", "Header") and patterns and name:
                        ref = f"request.{'queryparam' if item.tag == 'QueryParam' else 'header'}.{name}"
                        req = self._set_ref(req, ref, sample_pattern_value(patterns[0]))
        return req

    @staticmethod
    def _set_ref(req: Req, ref: str, value: str | None) -> Req:
        folded = fold(ref.strip())
        if folded.startswith("request.header.") and folded.count(".") == 2:
            return req.with_header(ref.strip().split(".", 2)[2], value)
        if folded.startswith("request.queryparam.") and folded.count(".") == 2:
            return req.with_param(ref.strip().split(".", 2)[2], value)
        return req

    def _reach(self, item: Placed) -> tuple[ProxyEndpoint, Req] | str:
        """A request that reaches ``item``'s step (with every credential), or why a2m has none."""
        endpoint = self.model.endpoint_of(item)
        if endpoint is None:
            return "no proxy endpoint routes to its target endpoint"
        constraints = self.model.path_constraints(item, endpoint)
        if isinstance(constraints, str):
            return constraints
        req = self._with_credentials(Req())
        try:
            nodes = [(parse_condition(cond), want) for cond, want in constraints]
        except Unknown as exc:
            return str(exc)
        for node, want in nodes:
            changed = satisfy(node, want, req)
            if changed is None:
                return "a2m can't build a request that meets the conditions on the way to its step"
            req = changed
        try:
            executed = tuple(self.model.run_call(endpoint, req, CaseState(), 0, False).executed)
        except Unknown as exc:
            if item.key not in exc.executed:
                return f"a test request can't be predicted on the way to its step: {exc}"
            executed = exc.executed
        if item.key not in executed:
            return "a2m can't build a request that reaches its step"
        return endpoint, req

    # ------------------------------------------------------------ cases

    def _cases_for(self, policy: Policy, item: Placed, index: int) -> None:
        if not policy.enabled:
            return
        builder: Callable[[Policy, Placed, ProxyEndpoint, Req, int], None] | None = {
            "VerifyAPIKey": self._verify_api_key,
            "SpikeArrest": self._spike_arrest,
            "Quota": self._quota,
            "AssignMessage": self._assign_message,
            "ExtractVariables": self._extract_variables,
            "RaiseFault": self._raise_fault,
            "BasicAuthentication": self._basic_auth,
            "AccessControl": self._access_control,
            "ResponseCache": self._response_cache,
        }.get(policy.type)
        if builder is None:
            self._skip(policy, f"a2m has no test battery for {policy.type} policies")
            return
        missing = self.not_live.get(item.key)
        if missing is not None:
            self._skip(policy, missing)
            return
        if item.side != REQUEST and policy.type not in ("RaiseFault",):
            self._skip(policy, "its step is in a response flow, which the battery does not check")
            return
        reached = self._reach(item)
        if isinstance(reached, str):
            self._skip(policy, reached)
            return
        endpoint, req = reached
        builder(policy, item, endpoint, req, index)

    def _add(
        self,
        policy: Policy,
        situation: str,
        endpoint: ProxyEndpoint,
        calls: Sequence[tuple[Req, bool]],
        index: int,
        *,
        check: Callable[[list[Outcome]], str | None] | None = None,
        headers: Callable[[list[Outcome]], dict[str, str | None] | None] | None = None,
    ) -> _Draft | None:
        """Predict ``calls`` and add the case; untested (with the reason) when a2m can't predict it."""
        waits = sum(1 for _, immediate in calls[1:] if not immediate)
        if waits * self.pace > MAX_CASE_SECONDS:
            self._skip(policy, f"{situation}: its calls would take longer than {MAX_CASE_SECONDS:.0f} seconds")
            return None
        state = CaseState()
        outcomes: list[Outcome] = []
        try:
            for number, (req, immediate) in enumerate(calls):
                outcomes.append(self.model.run_call(endpoint, req, state, number, immediate))
        except FaultRuleUnknown as exc:
            self._skip(policy, f"{situation}: not tested, {exc}")
            return None
        except Unknown as exc:
            self._skip(policy, f"{situation}: {exc}")
            return None
        problem = self._disabled_on_the_way(outcomes, policy.name)
        if problem is None and check is not None:
            problem = check(outcomes)
        if problem is not None:
            self._skip(policy, f"{situation}: {problem}")
            return None
        reaching = [o for o in outcomes if o.reached_backend]
        if headers is not None:
            expected = headers(outcomes)
            if expected is None:
                self._skip(policy, f"{situation}: the headers it sets on the backend call can't be predicted")
                return None
        else:
            expected = _common_asserted(reaching)
        writers = frozenset(
            o.headers[fold(k)].writer or "" for o in reaching for k in expected if fold(k) in o.headers
        ) - {""}
        fed = frozenset(f for o in reaching for k in expected if fold(k) in o.headers for f in o.headers[fold(k)].fed_by)
        base = endpoint.base_path or ""
        case = BatteryCase(
            name=f"{policy.name}-{situation}",
            policy=policy.name,
            policy_type=policy.type,
            situation=situation,
            calls=tuple(
                BatteryCall(_http(req, base), outcome.status, outcome.body, immediate)
                for (req, immediate), outcome in zip(calls, outcomes, strict=True)
            ),
            expected_backend_calls=len(reaching),
            expected_backend_headers=expected,
        )
        draft = _Draft(case, (index, len(self.drafts)), writers, fed)
        self.drafts.append(draft)
        return draft

    def _covered(self, keys: set[str], attribute: str) -> bool:
        return any(keys & getattr(d, attribute) for d in self.drafts)

    def _verify_api_key(self, policy: Policy, item: Placed, endpoint: ProxyEndpoint, req: Req, index: int) -> None:
        ref = _api_key_ref(policy)
        if not fold(ref).startswith(("request.header.", "request.queryparam.")):
            self._skip(policy, f"it reads the key from {ref!r}, which a test request does not set")
            return
        self._add(policy, "valid-key", endpoint, [(req, False)], index)
        self._add(policy, "missing-key", endpoint, [(self._set_ref(req, ref, None), False)], index)
        self._add(policy, "bad-key", endpoint, [(self._set_ref(req, ref, self.bad_key), False)], index)

    def _spike_arrest(self, policy: Policy, item: Placed, endpoint: ProxyEndpoint, req: Req, index: int) -> None:
        rate = spike_rate(policy)
        if rate is None:
            self._skip(policy, "its rate is not a fixed number per second or minute")
            return
        self._add(policy, "under-limit", endpoint, [(req, False)], index)
        interval = (1.0 if rate[1] == "ps" else 60.0) / rate[0]
        if interval < MIN_SPIKE_INTERVAL:
            self._skip(policy, f"over-limit: a pace of {interval * 1000:.0f} ms is too short to time a too-soon call")
            return
        spaced = min(rate[0], MAX_SPIKE_CALLS) if rate[1] == "ps" else 1
        calls = [(req, False)] * spaced + [(req, True)]
        self._add(policy, "over-limit", endpoint, calls, index, check=_last_status(429))

    def _quota(self, policy: Policy, item: Placed, endpoint: ProxyEndpoint, req: Req, index: int) -> None:
        allowance = quota_allowance(policy)
        if allowance is None:
            self._skip(policy, "its allowance or window is not a fixed number")
            return
        self._add(policy, "within-allowance", endpoint, [(req, False)], index)
        if allowance[0] > MAX_QUOTA_ALLOWANCE:
            self._skip(
                policy, f"over-allowance: {allowance[0]} calls are too many to use up in a test "
                f"(at most {MAX_QUOTA_ALLOWANCE})"
            )
            return
        calls = [(req, False)] * (allowance[0] + 1)
        self._add(policy, "over-allowance", endpoint, calls, index, check=_last_status(429))

    def _assign_message(self, policy: Policy, item: Placed, endpoint: ProxyEndpoint, req: Req, index: int) -> None:
        names = _assigned_headers(policy)
        if not names:
            self._skip(policy, "it changes nothing the battery checks (only request headers are checked)")
            return
        keys = {p.key for p in self.model.placed_steps() if p.step.policy == policy.name}

        def mine(outcomes: list[Outcome]) -> dict[str, str | None] | None:
            reaching = [o for o in outcomes if o.reached_backend]
            if not reaching:
                return None
            found: dict[str, str | None] = {}
            for name in names:
                state = reaching[0].headers.get(fold(name))
                if state is not None and not state.known:
                    return None
                found[name] = state.value if state is not None else None
            return found

        if self._covered(keys, "writers"):
            self.covered.add(policy.name)
        else:
            self._add(policy, "header-set", endpoint, [(req, False)], index, headers=mine)
        if item.step.condition:
            try:
                node: Node = parse_condition(item.step.condition)
            except Unknown as exc:
                self._skip(policy, f"condition-false: {exc}")
                return
            falsified = satisfy(node, False, req)
            if falsified is None:
                self._skip(policy, "condition-false: a2m can't build a request that makes its condition false")
                return
            self._add(policy, "condition-false", endpoint, [(falsified, False)], index, headers=mine)

    def _extract_variables(self, policy: Policy, item: Placed, endpoint: ProxyEndpoint, req: Req, index: int) -> None:
        keys = {p.key for p in self.model.placed_steps() if p.step.policy == policy.name}
        if self._covered(keys, "fed_by"):
            self.covered.add(policy.name)
            return
        draft = self._add(policy, "extracted-value-used", endpoint, [(req, False)], index)
        if draft is not None and not (draft.fed_by & keys):
            self.drafts.remove(draft)
            self._skip(
                policy, "extracted-value-used: no value it extracts reaches the backend in a way the battery checks"
            )

    def _raise_fault(self, policy: Policy, item: Placed, endpoint: ProxyEndpoint, req: Req, index: int) -> None:
        self._add(policy, "fault-raised", endpoint, [(req, False)], index, check=_stopped_by(item.key))

    def _basic_auth(self, policy: Policy, item: Placed, endpoint: ProxyEndpoint, req: Req, index: int) -> None:
        if fold(text(child(policy.settings, "Operation")) or "") != "decode":
            self._skip(policy, "the battery checks only the Decode operation")
            return
        source = text(child(policy.settings, "Source")) or ""
        self._add(policy, "correct-credentials", endpoint, [(req, False)], index)
        self._add(policy, "missing-credentials", endpoint, [(self._set_ref(req, source, None), False)], index)

    def _access_control(self, policy: Policy, item: Placed, endpoint: ProxyEndpoint, req: Req, index: int) -> None:
        def situation(outcomes: list[Outcome]) -> str:
            return "denied-address" if outcomes[0].stopped_by == item.key else "allowed-address"

        try:
            probe = self.model.run_call(endpoint, req, CaseState(), 0, False)
        except Unknown as exc:
            self._skip(policy, str(exc))
            return
        self._add(policy, situation([probe]), endpoint, [(req, False)], index)

    def _response_cache(self, policy: Policy, item: Placed, endpoint: ProxyEndpoint, req: Req, index: int) -> None:
        def one_hit(outcomes: list[Outcome]) -> str | None:
            hits = sum(1 for o in outcomes if o.reached_backend)
            return None if hits == 1 else f"the cache would not answer the repeated calls ({hits} backend calls)"

        calls = [(req, False)] * CACHE_CALLS
        self._add(policy, "repeated-call-cached", endpoint, calls, index, check=one_hit)


@dataclass(frozen=True, slots=True)
class HeaderChanges:
    """The headers the proxy's own steps may change in Apigee (lower case), from their write models.

    ``request``: request headers a request-side step sets or removes before the target; ``response``:
    response headers a response-side step sets or removes. ``*_any``: some step there may change every
    header (a policy a2m has no write model for, such as JavaScript or a FlowCallout).
    """

    request: frozenset[str] = frozenset()
    request_any: bool = False
    response: frozenset[str] = frozenset()
    response_any: bool = False


def header_changes(bundle: Bundle) -> HeaderChanges:
    """Which request and response headers the proxy's flow steps may change (see :class:`HeaderChanges`)."""
    policies = {p.name: p for p in bundle.policies}
    request: set[str] = set()
    response: set[str] = set()
    request_any = response_any = False
    for item in Model(bundle, {}).placed_steps():
        policy = policies.get(item.step.policy)
        if policy is None or not policy.enabled:
            continue
        if item.side == REQUEST:
            for name, _ in registry.request_changes(policy, direction=REQUEST).headers:
                if name == ANY_HEADER:
                    request_any = True
                else:
                    request.add(fold(name))
        else:
            for write in registry.variable_writes(policy, direction="response"):
                if write == ANY_HEADER or write == RESPONSE_HEADER_PREFIX:
                    response_any = True
                elif write.startswith(RESPONSE_HEADER_PREFIX):
                    response.add(fold(write[len(RESPONSE_HEADER_PREFIX) :]))
    return HeaderChanges(frozenset(request), request_any, frozenset(response), response_any)


def _http(req: Req, base_path: str) -> HttpRequest:
    return HttpRequest(req.method, req.path(base_path), dict(req.headers))


def _api_key_ref(policy: Policy) -> str:
    api_key = child(policy.settings, "APIKey")
    return (api_key.attributes.get("ref", "") if api_key is not None else "").strip()


def _assigned_headers(policy: Policy) -> list[str]:
    """The request headers an AssignMessage sets, adds or removes (in that order of appearance)."""
    settings = policy.settings
    assign_to = child(settings, "AssignTo")
    if assign_to is not None and (
        fold((assign_to.attributes.get("type") or REQUEST).strip()) != REQUEST
        or fold((assign_to.attributes.get("createNew") or "").strip()) == "true"
        or (assign_to.text or "").strip()
    ):
        return []
    names: list[str] = []
    for op in ("Remove", "Add", "Set"):
        for header in children(child(child(settings, op), "Headers"), "Header"):
            name = header.attributes.get("name", "")
            if name and fold(name) not in {fold(n) for n in names}:
                names.append(name)
    return names


def _common_asserted(reaching: list[Outcome]) -> dict[str, str | None]:
    """Headers some step set on every backend call, with the same known value on each."""
    if not reaching:
        return {}
    first = reaching[0].asserted_headers()
    found: dict[str, str | None] = {}
    for key, state in first.items():
        if all(o.asserted_headers().get(key) == state for o in reaching[1:]):
            found[state.name] = state.value
    return found


def _last_status(status: int) -> Callable[[list[Outcome]], str | None]:
    def check(outcomes: list[Outcome]) -> str | None:
        last = outcomes[-1].status
        return None if last == status else f"the last call would get {last}, not {status}"

    return check


def _stopped_by(key: str) -> Callable[[list[Outcome]], str | None]:
    def check(outcomes: list[Outcome]) -> str | None:
        return None if outcomes[0].stopped_by == key else "its step would not answer the call"

    return check


__all__ = [
    "Battery",
    "BatteryCall",
    "BatteryCase",
    "HeaderChanges",
    "build_battery",
    "header_changes",
    "read_properties",
    "time_window_flags",
]


def fault_rule_policies(bundle: Bundle) -> set[str]:
    """Names of the policies a FaultRule or DefaultFaultRule of any endpoint runs."""
    found: set[str] = set()
    endpoints: list[ProxyEndpoint | TargetEndpoint] = [*bundle.proxy_endpoints, *bundle.target_endpoints]
    for endpoint in endpoints:
        for rule in endpoint.fault_rules:
            found.update(step.policy for step in rule.steps)
        if endpoint.default_fault_rule is not None:
            found.update(step.policy for step in endpoint.default_fault_rule.steps)
    return found


def recorded_key_properties(
    bundle: Bundle, app_dir: Path, recorded: Iterable[tuple[HttpRequest, int]]
) -> tuple[dict[str, str], tuple[str, ...]]:
    """Settings that allow, in the deployed copy only, the API keys a golden recording shows as valid.

    For each VerifyAPIKey whose allowed-keys property in the generated properties file is empty, the
    key each recorded request presented where the policy reads it (header or query parameter) counts
    as valid when Apigee's recorded answer was not 401. Returns the settings and a note per policy for
    the report (the keys themselves are never written into the note).
    """
    props = read_properties(app_dir)
    calls = list(recorded)
    settings: dict[str, str] = {}
    notes: list[str] = []
    for policy in bundle.policies:
        if policy.type != "VerifyAPIKey" or not policy.enabled:
            continue
        prop = f"verifyapikey.{key_part(policy.name)}.allowedKeys"
        if prop not in props or any(k.strip() for k in props[prop].split(",")):
            continue
        ref = _api_key_ref(policy)
        keys: list[str] = []
        for request, status in calls:
            if status == 401:
                continue
            value = _request_value(request, ref)
            if value and "," not in value and value not in keys:
                keys.append(value)
        if keys:
            settings[prop] = ",".join(keys)
            notes.append(
                f"VerifyAPIKey {policy.name} has no allowed key in {PROPERTIES_PATH[-1]}, so the replay allowed the "
                f"{len(keys)} key(s) the recorded requests presented with a non-401 answer, in the deployed copy only"
            )
    return settings, tuple(notes)


def _request_value(request: HttpRequest, ref: str) -> str | None:
    """The value ``ref`` (request.header.X or request.queryparam.X) reads from ``request``, as VerifyAPIKey reads it."""
    folded = fold(ref.strip())
    if folded.startswith("request.header.") and folded.count(".") == 2:
        name = fold(ref.strip().split(".", 2)[2])
        value = next((v for k, v in dict(request.headers).items() if fold(str(k)) == name), None)
        return value.split(",", 1)[0].strip() if value is not None else None
    if folded.startswith("request.queryparam.") and folded.count(".") == 2:
        name = ref.strip().split(".", 2)[2]
        values = parse_qs(urlsplit(request.path).query, keep_blank_values=True).get(name)
        return values[0] if values else None
    return None
